In [ ]:
# Pandas
# Pandas is a powerful and flexible Python package that allows you to work with labeled and
# time series data. It also provides statistics methods, enables plotting, and more.
# One crucial feature of pandas is its ability to write and read Excel, CSV, and many other types of files.

# Reading An Excel File
# Reading A CSV File
# Reading tab-delimited file
# Reading A JSON File
# Uploading Local Files In Google Colab

In [ ]:
import pandas as pd

In [ ]:
# Reading an Excel File
# read_excel()
# pd.read_excel('location and name of file')
data = pd.read_excel('https://raw.githubusercontent.com/yash240990/Python/master/sampleExcelData.xlsx')
data

,id,first_name,last_name,email,gender,ip_address
0,1,Merle,Draisey,mdraisey0@squarespace.com,Bigender,20.70.199.51
1,2,Casey,Sheach,csheach1@deviantart.com,Male,226.126.229.167
2,3,Darya,Leivers,dleivers2@imgur.com,Female,247.209.88.235
3,4,Fancie,Casebourne,fcasebourne3@g.co,Female,172.34.162.239
4,5,Jenilee,Vsanelli,jvsanelli4@fc2.com,Female,200.104.246.2
...,...,...,...,...,...,...
995,996,Lutero,Yurov,lyurovrn@un.org,Male,95.146.16.187
996,997,Verla,Peery,vpeeryro@com.com,Female,172.90.253.234
997,998,Fran,Langran,flangranrp@ft.com,Male,123.179.99.154
998,999,Gabbi,Cummins,gcumminsrq@jugem.jp,Female,190.13.174.159
999,1000,Gloriane,Marc,gmarcrr@businessweek.com,Female,139.87.192.32

In [ ]:
type(data)

pandas.core.frame.DataFrame

In [ ]:
# Reading The Data From a Different Sheet
# Load The Entire Excel Workbook

excelFile = pd.ExcelFile('https://raw.githubusercontent.com/yash240990/Python/master/sampleExcelData.xlsx')
excelFile.sheet_names

['data', 'Sheet2']

In [ ]:
data = pd.read_excel(excelFile, 'Sheet2')
data

   first_name    last_name                                 email
0       Merle      Draisey             mdraisey0@squarespace.com
1       Casey       Sheach               csheach1@deviantart.com
2       Darya      Leivers                   dleivers2@imgur.com
3      Fancie   Casebourne                     fcasebourne3@g.co
4     Jenilee     Vsanelli                    jvsanelli4@fc2.com
5    Charmian    Drinkhall       cdrinkhall5@theglobeandmail.com
6     Janessa       Kivell                 jkivell6@linkedin.com
7       Mirna       Heinsh                  mheinsh7@spotify.com
8       Darby          Lax                   dlax8@people.com.cn
9       Meryl        Riehm                 mriehm9@princeton.edu
10       Anne        Brody                    abrodya@sphinn.com
11       Puff    Langsbury             plangsburyb@canalblog.com
12       Tina      Gregoli                  tgregolic@sfgate.com
13     Barbie       Dahlen                     bdahlend@narod.ru
14     Andeee  Dobrovolski  adobrovolskie@networkadvertising.org
15    Ainsley       Friman                      afrimanf@irs.gov
16        Bil     Shalcros                 bshalcrosg@dion.ne.jp
17    Raimund     Outridge                   routridgeh@lulu.com
18     Whitby     Millward                    wmillwardi@ask.com
19        Rob      Boarder                       rboarderj@51.la
20      Nicky     Curthoys                    ncurthoysk@pbs.org

In [ ]:
# Reading A CSV File
# Comma Separated Value
data = pd.read_csv('https://raw.githubusercontent.com/yash240990/Python/master/Position_Salaries.csv')
data

            Position  Level   Salary
0   Business Analyst      1    45000
1  Junior Consultant      2    50000
2  Senior Consultant      3    60000
3            Manager      4    80000
4    Country Manager      5   110000
5     Region Manager      6   150000
6            Partner      7   200000
7     Senior Partner      8   300000
8            C-level      9   500000
9                CEO     10  1000000

In [ ]:
# Reading tab-delimited file
# Reading the content of Excel File saved with .txt format

data = pd.read_csv('https://raw.githubusercontent.com/prefuse/Prefuse/refs/heads/master/data/fisher.iris.txt',
                   sep='\t')
data

     SepalLength  SepalWidth  PetalLength  PetalWidth  Species Species Name
0             50          33           14           2        1       Setosa
1             64          28           56          22        3    Virginica
2             65          28           46          15        2   Versicolor
3             67          31           56          24        3    Virginica
4             63          28           51          15        3    Virginica
..           ...         ...          ...         ...      ...          ...
145           52          35           15           2        1       Setosa
146           58          28           51          24        3    Virginica
147           67          30           50          17        2   Versicolor
148           63          33           60          25        3    Virginica
149           53          37           15           2        1       Setosa

[150 rows x 6 columns]

In [ ]:
# Reading a JSON
data = pd.read_json('https://raw.githubusercontent.com/yash240990/Python/master/simple.json')
data

     id   name  math  physics  chemistry
0  A001    Tom    60       66         61
1  A002  James    89       76         51
2  A003  Jenny    79       90         78

In [ ]:
# Uploading Local Files In Google Colab

from google.colab import files
uploaded = files.upload()         # file upload wizard

Saving sample.csv to sample.csv

In [ ]:
!ls # List The Files

sample.csv  sample_data

In [ ]:
data = pd.read_csv('sample.csv')
data

,id,first_name,last_name,email,gender,department,company name,salary
0,1,Demetris,McNellis,dmcnellis0@msu.edu,Male,Marketing,Photobean,2792
1,2,Grove,Savary,gsavary1@latimes.com,Male,Services,Gigabox,5573
2,3,Barnie,Garvan,bgarvan2@trellian.com,Male,Research and Development,Wikivu,7900
3,4,Abbott,Dunrige,adunrige3@intel.com,Male,Legal,Realfire,6872
4,5,Adriano,Streater,astreater4@apple.com,Male,Marketing,Jabbersphere,7735
...,...,...,...,...,...,...,...,...
995,996,Yolanthe,McIlmorow,ymcilmorowrn@deliciousdays.com,Female,Marketing,Jayo,4136
996,997,Dino,Reignard,dreignardro@time.com,Male,Product Management,Skimia,7599
997,998,Hort,Fagge,hfaggerp@reddit.com,Male,Training,Zoozzy,5148
998,999,Penrod,McGeachie,pmcgeachierq@wikia.com,Male,Sales,Tambee,5408
999,1000,Durand,Cunrado,dcunradorr@photobucket.com,Male,Sales,Yamia,5712